// This code was generated by the Gardens Point Parser Generator
// Copyright (c) Wayne Kelly, John Gough, QUT 2005-2014
// (see accompanying GPPGcopyright.rtf)

// GPPG version 1.5.2
// Machine:  DESKTOP-PIILLQS
// DateTime: 08.06.2021 21:09:39
// UserName: wpodm
// Input file <.\compiler.y - 08.06.2021 21:09:36>

// options: lines gplex

using System;
using System.Collections.Generic;
using System.CodeDom.Compiler;
using System.Globalization;
using System.Text;
using QUT.Gppg;

namespace GardensPoint
{
public enum Tokens {error=2,EOF=3,Program=4,OpenBlock=5,Eof=6,
    CloseBlock=7,Int=8,Bool=9,Double=10,Coma=11,Semicolon=12,
    Assignment=13,Identificator=14,IntNumber=15,RealNumber=16,Boolean=17};

public struct ValueType
#line 7 ".\compiler.y"
{
public List<string> varNames;
public List<Compiler.INode> nodesList;
public string val;
public Compiler.Types types;
public Compiler.INode node;
public Compiler.Pair constantType;
public Compiler.ExpresionNode expresionNode;
}
#line default
// Abstract base class for GPLEX scanners
[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.5.2")]
public abstract class ScanBase : AbstractScanner<ValueType,LexLocation> {
  private LexLocation __yylloc = new LexLocation();
  public override LexLocation yylloc { get { return __yylloc; } set { __yylloc = value; } }
  protected virtual bool yywrap() { return true; }
}

// Utility class for encapsulating token information
[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.5.2")]
public class ScanObj {
  public int token;
  public ValueType yylval;
  public LexLocation yylloc;
  public ScanObj( int t, ValueType val, LexLocation loc ) {
    this.token = t; this.yylval = val; this.yylloc = loc;
  }
}

[GeneratedCodeAttribute( "Gardens Point Parser Generator", "1.5.2")]
public class Parser: ShiftReduceParser<ValueType, LexLocation>
{
#pragma warning disable 649
  private static Dictionary<int, string> aliases;
#pragma warning restore 649
  private static Rule[] rules = new Rule[23];
  private static State[] states = new State[30];
  private static string[] nonTerms = new string[] {
      "type", "multideclarations", "body", "declaration", "statement", "singleOperation", 
      "constant", "expression", "declarations", "statements", "start", "$accept", 
      };

  static Parser() {
    states[0] = new State(new int[]{4,3},new int[]{-11,1});
    states[1] = new State(new int[]{3,2});
    states[2] = new State(-1);
    states[3] = new State(new int[]{5,6,6,-4},new int[]{-3,4});
    states[4] = new State(new int[]{6,5});
    states[5] = new State(-2);
    states[6] = new State(-6,new int[]{-9,7});
    states[7] = new State(new int[]{8,27,10,28,9,29,7,-9,14,-9,15,-9,16,-9,17,-9},new int[]{-10,8,-4,21,-1,22});
    states[8] = new State(new int[]{7,9,14,14,15,18,16,19,17,20},new int[]{-5,10,-6,11,-8,13,-7,17});
    states[9] = new State(-3);
    states[10] = new State(-8);
    states[11] = new State(new int[]{12,12});
    states[12] = new State(-10);
    states[13] = new State(-12);
    states[14] = new State(new int[]{13,15});
    states[15] = new State(new int[]{14,14,15,18,16,19,17,20},new int[]{-8,16,-7,17});
    states[16] = new State(-13);
    states[17] = new State(-14);
    states[18] = new State(-15);
    states[19] = new State(-16);
    states[20] = new State(-17);
    states[21] = new State(-5);
    states[22] = new State(-22,new int[]{-2,23});
    states[23] = new State(new int[]{14,24});
    states[24] = new State(new int[]{12,25,11,26});
    states[25] = new State(-7);
    states[26] = new State(-21);
    states[27] = new State(-18);
    states[28] = new State(-19);
    states[29] = new State(-20);

    for (int sNo = 0; sNo < states.Length; sNo++) states[sNo].number = sNo;

    rules[1] = new Rule(-12, new int[]{-11,3});
    rules[2] = new Rule(-11, new int[]{4,-3,6});
    rules[3] = new Rule(-3, new int[]{5,-9,-10,7});
    rules[4] = new Rule(-3, new int[]{});
    rules[5] = new Rule(-9, new int[]{-9,-4});
    rules[6] = new Rule(-9, new int[]{});
    rules[7] = new Rule(-4, new int[]{-1,-2,14,12});
    rules[8] = new Rule(-10, new int[]{-10,-5});
    rules[9] = new Rule(-10, new int[]{});
    rules[10] = new Rule(-5, new int[]{-6,12});
    rules[11] = new Rule(-5, new int[]{});
    rules[12] = new Rule(-6, new int[]{-8});
    rules[13] = new Rule(-8, new int[]{14,13,-8});
    rules[14] = new Rule(-8, new int[]{-7});
    rules[15] = new Rule(-7, new int[]{15});
    rules[16] = new Rule(-7, new int[]{16});
    rules[17] = new Rule(-7, new int[]{17});
    rules[18] = new Rule(-1, new int[]{8});
    rules[19] = new Rule(-1, new int[]{10});
    rules[20] = new Rule(-1, new int[]{9});
    rules[21] = new Rule(-2, new int[]{-2,14,11});
    rules[22] = new Rule(-2, new int[]{});
  }

  protected override void Initialize() {
    this.InitSpecialTokens((int)Tokens.error, (int)Tokens.EOF);
    this.InitStates(states);
    this.InitRules(rules);
    this.InitNonTerminals(nonTerms);
  }

  protected override void DoAction(int action)
  {
#pragma warning disable 162, 1522
    switch (action)
    {
      case 2: // start -> Program, body, Eof
#line 30 ".\compiler.y"
            {
                Compiler.GenBody(ValueStack[ValueStack.Depth-2].node);
            }
#line default
        break;
      case 3: // body -> OpenBlock, declarations, statements, CloseBlock
#line 36 ".\compiler.y"
            {
                CurrentSemanticValue.node = new Compiler.BodyNode(ValueStack[ValueStack.Depth-3].nodesList,ValueStack[ValueStack.Depth-2].nodesList);
            }
#line default
        break;
      case 5: // declarations -> declarations, declaration
#line 43 ".\compiler.y"
                {
                    ValueStack[ValueStack.Depth-2].nodesList.Add(ValueStack[ValueStack.Depth-1].node);
                    CurrentSemanticValue.nodesList = ValueStack[ValueStack.Depth-2].nodesList;
                }
#line default
        break;
      case 6: // declarations -> /* empty */
#line 47 ".\compiler.y"
               { CurrentSemanticValue.nodesList = new List<Compiler.INode>(); }
#line default
        break;
      case 7: // declaration -> type, multideclarations, Identificator, Semicolon
#line 51 ".\compiler.y"
              {
                    Compiler.actualType = ValueStack[ValueStack.Depth-4].types;
                    if(Compiler.IsIdentyficatorOccupied(ValueStack[ValueStack.Depth-4].types,ValueStack[ValueStack.Depth-2].val))
                    {
                        Console.WriteLine("line: error: such variable name already exists");
                    }
                    else
                    {
                        ValueStack[ValueStack.Depth-3].varNames.Add(ValueStack[ValueStack.Depth-2].val);
                        CurrentSemanticValue.node = new Compiler.DeclarationNode(ValueStack[ValueStack.Depth-4].types,ValueStack[ValueStack.Depth-3].varNames);
                    }
              }
#line default
        break;
      case 8: // statements -> statements, statement
#line 66 ".\compiler.y"
                {
                    ValueStack[ValueStack.Depth-2].nodesList.Add(ValueStack[ValueStack.Depth-1].node);
                    CurrentSemanticValue.nodesList = ValueStack[ValueStack.Depth-2].nodesList;
                }
#line default
        break;
      case 9: // statements -> /* empty */
#line 70 ".\compiler.y"
              { CurrentSemanticValue.nodesList = new List<Compiler.INode>(); }
#line default
        break;
      case 10: // statement -> singleOperation, Semicolon
#line 73 ".\compiler.y"
                                        { CurrentSemanticValue.node = new Compiler.StatementNode(ValueStack[ValueStack.Depth-2].node); }
#line default
        break;
      case 12: // singleOperation -> expression
#line 77 ".\compiler.y"
                             { CurrentSemanticValue.node = new Compiler.SingleOperationNode(ValueStack[ValueStack.Depth-1].expresionNode); }
#line default
        break;
      case 13: // expression -> Identificator, Assignment, expression
#line 81 ".\compiler.y"
            {
                if(Compiler.variables.ContainsKey(ValueStack[ValueStack.Depth-3].val))
                {
                    CurrentSemanticValue.expresionNode = new Compiler.AssignmentExpresionNode(new Compiler.Pair(Compiler.variables[ValueStack[ValueStack.Depth-3].val],ValueStack[ValueStack.Depth-3].val), ValueStack[ValueStack.Depth-1].expresionNode);
                }
                else
                {
                    Console.WriteLine("line: error: such variable not exists");
                }
            }
#line default
        break;
      case 14: // expression -> constant
#line 92 ".\compiler.y"
                {
                    CurrentSemanticValue.expresionNode = new Compiler.ConstantExpresionNode(ValueStack[ValueStack.Depth-1].constantType);
                }
#line default
        break;
      case 15: // constant -> IntNumber
#line 97 ".\compiler.y"
                     { CurrentSemanticValue.constantType = new Compiler.Pair(Compiler.Types.IntegerType, ValueStack[ValueStack.Depth-1].val); }
#line default
        break;
      case 16: // constant -> RealNumber
#line 98 ".\compiler.y"
                      { CurrentSemanticValue.constantType = new Compiler.Pair(Compiler.Types.DoubleType, ValueStack[ValueStack.Depth-1].val); }
#line default
        break;
      case 17: // constant -> Boolean
#line 99 ".\compiler.y"
                   { CurrentSemanticValue.constantType = new Compiler.Pair(Compiler.Types.BooleanType, ValueStack[ValueStack.Depth-1].val); }
#line default
        break;
      case 18: // type -> Int
#line 102 ".\compiler.y"
                   {CurrentSemanticValue.types = Compiler.Types.IntegerType;}
#line default
        break;
      case 19: // type -> Double
#line 103 ".\compiler.y"
                      {CurrentSemanticValue.types = Compiler.Types.DoubleType;}
#line default
        break;
      case 20: // type -> Bool
#line 104 ".\compiler.y"
                    {CurrentSemanticValue.types = Compiler.Types.BooleanType;}
#line default
        break;
      case 21: // multideclarations -> multideclarations, Identificator, Coma
#line 108 ".\compiler.y"
                    {
                        if(Compiler.IsIdentyficatorOccupied(Compiler.actualType,ValueStack[ValueStack.Depth-2].val))
                        {
                            Console.WriteLine("line: error: such variable name already exists");
                        }
                        else
                        {
                            ValueStack[ValueStack.Depth-3].varNames.Add(ValueStack[ValueStack.Depth-2].val);
                            CurrentSemanticValue.varNames = ValueStack[ValueStack.Depth-3].varNames;
                        }
                    }
#line default
        break;
      case 22: // multideclarations -> /* empty */
#line 119 ".\compiler.y"
                    { CurrentSemanticValue.varNames = new List<string>(); }
#line default
        break;
    }
#pragma warning restore 162, 1522
  }

  protected override string TerminalToString(int terminal)
  {
    if (aliases != null && aliases.ContainsKey(terminal))
        return aliases[terminal];
    else if (((Tokens)terminal).ToString() != terminal.ToString(CultureInfo.InvariantCulture))
        return ((Tokens)terminal).ToString();
    else
        return CharToString((char)terminal);
  }

#line 123 ".\compiler.y"

public Parser(Scanner scanner) : base(scanner) { }
#line default
}
}
